# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'CircleOfFriends' do

pod 'SDWebImage', '~> 3.8.1'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'YYText', '~> 1.0.5'
pod 'Masonry', '~> 1.0.1'
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CircleOfFriends

  target 'CircleOfFriendsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CircleOfFriendsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
